
CREATE TABLE IF NOT EXISTS BaiXe (
    BaiXeId INT AUTO_INCREMENT PRIMARY KEY,
    TenBaiXe VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255),
    SucChuaTong INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS KhuVuc (
    KhuVucId INT AUTO_INCREMENT PRIMARY KEY,
    BaiXeId INT,
    TenKhuVuc VARCHAR(50) NOT NULL,
    LoaiXeChoPhep VARCHAR(50), 
    FOREIGN KEY (BaiXeId) REFERENCES BaiXe(BaiXeId)
);

CREATE TABLE IF NOT EXISTS ChoDoXe (
    ChoDoId INT AUTO_INCREMENT PRIMARY KEY,
    KhuVucId INT,
    MaSoCho VARCHAR(20) NOT NULL UNIQUE, 
    TrangThai BOOLEAN DEFAULT TRUE, 
    FOREIGN KEY (KhuVucId) REFERENCES KhuVuc(KhuVucId)
);


CREATE TABLE IF NOT EXISTS LichSuDoXe (
    LichSuId INT AUTO_INCREMENT PRIMARY KEY,
    ChoDoId INT,
    BienSoXe VARCHAR(20) NOT NULL,
    ThoiGianVao DATETIME DEFAULT CURRENT_TIMESTAMP,
    ThoiGianRa DATETIME,
    FOREIGN KEY (ChoDoId) REFERENCES ChoDoXe(ChoDoId)
);