USE QuanLyBaiXe;
GO


IF OBJECT_ID('HinhAnhXe', 'U') IS NOT NULL DROP TABLE HinhAnhXe;
IF OBJECT_ID('LuotGui', 'U') IS NOT NULL DROP TABLE LuotGui;
IF OBJECT_ID('VeXe', 'U') IS NOT NULL DROP TABLE VeXe;
IF OBJECT_ID('Xe', 'U') IS NOT NULL DROP TABLE Xe;
IF OBJECT_ID('LoaiXe', 'U') IS NOT NULL DROP TABLE LoaiXe;
GO


CREATE TABLE LoaiXe
(
    LoaiXeId INT IDENTITY(1,1) PRIMARY KEY,
    TenLoaiXe NVARCHAR(50) NOT NULL,
    -- NVARCHAR lưu được tiếng Việt
    GiaTienLuot DECIMAL(10, 2) NOT NULL DEFAULT 0,
    GiaTienThang DECIMAL(10, 2) NOT NULL DEFAULT 0
);


CREATE TABLE Xe
(
    XeId INT IDENTITY(1,1) PRIMARY KEY,
    BienSo VARCHAR(20) NOT NULL UNIQUE,
    LoaiXeId INT NOT NULL,
    CONSTRAINT FK_Xe_LoaiXe FOREIGN KEY (LoaiXeId) REFERENCES LoaiXe(LoaiXeId)
);


CREATE TABLE VeXe
(
    VeXeId INT IDENTITY(1,1) PRIMARY KEY,
    MaVe VARCHAR(50) NOT NULL UNIQUE,
    LoaiVe NVARCHAR(20) NOT NULL,
    TrangThai NVARCHAR(20) DEFAULT N'TRỐNG'

);


CREATE TABLE LuotGui
(
    LuotGuiId INT IDENTITY(1,1) PRIMARY KEY,
    Thoigianvao DATETIME NOT NULL DEFAULT GETDATE(),
    Thoigianra DATETIME NULL,
    PhiGui DECIMAL(10, 2) DEFAULT 0,
    XeId INT NOT NULL,
    VeXeId INT NOT NULL,
    CONSTRAINT FK_LuotGui_Xe FOREIGN KEY (XeId) REFERENCES Xe(XeId),
    CONSTRAINT FK_LuotGui_VeXe FOREIGN KEY (VeXeId) REFERENCES VeXe(VeXeId)
);

CREATE TABLE HinhAnhXe
(
    HinhAnhId INT IDENTITY(1,1) PRIMARY KEY,
    LuotGuiId INT NOT NULL,
    DuongDanAnh VARCHAR(255) NOT NULL,
    LoaiHinh VARCHAR(10) NOT NULL,
    CONSTRAINT FK_HinhAnh_LuotGui FOREIGN KEY (LuotGuiId) REFERENCES LuotGui(LuotGuiId)
);
ALTER TABLE Xe ADD MauXe NVARCHAR(30);
GO