USE QuanLyBaiXe;
GO


IF OBJECT_ID('LuotGui', 'U') IS NOT NULL DROP TABLE LuotGui;
IF OBJECT_ID('VeGui', 'U') IS NOT NULL DROP TABLE VeGui;
IF OBJECT_ID('TrangThaiVe', 'U') IS NOT NULL DROP TABLE TrangThaiVe;
IF OBJECT_ID('LoaiVe', 'U') IS NOT NULL DROP TABLE LoaiVe;
GO

CREATE TABLE LoaiVe
(
    LoaiVeId INT IDENTITY(1,1) PRIMARY KEY,
    TenLoaiVe NVARCHAR(50) NOT NULL UNIQUE

);


CREATE TABLE TrangThaiVe
(
    TrangThaiId INT IDENTITY(1,1) PRIMARY KEY,
    TenTrangThai NVARCHAR(50) NOT NULL UNIQUE

);


CREATE TABLE VeGui
(
    VeGuiId INT IDENTITY(1,1) PRIMARY KEY,
    LoaiVeId INT,
    TrangThaiId INT,
    NgayTao DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_VeGui_LoaiVe FOREIGN KEY (LoaiVeId) REFERENCES LoaiVe(LoaiVeId),
    CONSTRAINT FK_VeGui_TrangThai FOREIGN KEY (TrangThaiId) REFERENCES TrangThaiVe(TrangThaiId)
);


CREATE TABLE LuotGui
(
    LuotGuiId INT IDENTITY(1,1) PRIMARY KEY,
    VeGuiId INT,
    ThoiGianGui DATETIME DEFAULT GETDATE(),
    KetQua NVARCHAR(100),
    CONSTRAINT FK_LuotGui_VeGui FOREIGN KEY (VeGuiId) REFERENCES VeGui(VeGuiId)
);
GO