CREATE TABLE IF NOT EXISTS LoaiVe (
    LoaiVeId INT AUTO_INCREMENT PRIMARY KEY,
    TenLoaiVe VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TrangThaiVe (
    TrangThaiId INT AUTO_INCREMENT PRIMARY KEY,
    TenTrangThai VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS VeGui (
    VeGuiId INT AUTO_INCREMENT PRIMARY KEY,
    LoaiVeId INT,
    TrangThaiId INT,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LoaiVeId) REFERENCES LoaiVe(LoaiVeId),
    FOREIGN KEY (TrangThaiId) REFERENCES TrangThaiVe(TrangThaiId)
);

CREATE TABLE IF NOT EXISTS LuotGui (
    LuotGuiId INT AUTO_INCREMENT PRIMARY KEY,
    VeGuiId INT,
    ThoiGianGui DATETIME DEFAULT CURRENT_TIMESTAMP,
    KetQua VARCHAR(100),
    FOREIGN KEY (VeGuiId) REFERENCES VeGui(VeGuiId)
);
