USE QuanLyBaiXe;
GO


IF OBJECT_ID('HinhAnhXe', 'U') IS NOT NULL DROP TABLE HinhAnhXe;
IF OBJECT_ID('LichSuDoXe', 'U') IS NOT NULL DROP TABLE LichSuDoXe;
IF OBJECT_ID('LuotGui', 'U') IS NOT NULL DROP TABLE LuotGui;
IF OBJECT_ID('Xe', 'U') IS NOT NULL DROP TABLE Xe;
IF OBJECT_ID('VeXe', 'U') IS NOT NULL DROP TABLE VeXe;
IF OBJECT_ID('LoaiXe', 'U') IS NOT NULL DROP TABLE LoaiXe; 
GO


CREATE TABLE LoaiXe
(
    LoaiXeld INT IDENTITY(1,1) PRIMARY KEY,
    TenLoaiXe NVARCHAR(50) NOT NULL,
    GiaTienLuot DECIMAL(10, 2) NOT NULL DEFAULT 0,
    GiaTienThang DECIMAL(10, 2) NOT NULL DEFAULT 0
);

CREATE TABLE Xe
(
    Xeld INT IDENTITY(1,1) PRIMARY KEY,
    BienSo VARCHAR(20) NOT NULL UNIQUE,
    MauXe NVARCHAR(30),
    LoaiXeld INT NOT NULL,
    CONSTRAINT FK_Xe_LoaiXe FOREIGN KEY (LoaiXeld) REFERENCES LoaiXe(LoaiXeld)
);

CREATE TABLE VeXe
(
    VeXeld INT IDENTITY(1,1) PRIMARY KEY,
    MaVe VARCHAR(50) NOT NULL UNIQUE,
    LoaiVe NVARCHAR(20) NOT NULL,
    TrangThai NVARCHAR(20) DEFAULT N'TRỐNG'
);

CREATE TABLE LuotGui
(
    LuotGuiId INT IDENTITY(1,1) PRIMARY KEY,
    ThoiGianVao DATETIME NOT NULL DEFAULT GETDATE(),
    ThoiGianRa DATETIME NULL,
    PhiGui DECIMAL(10, 2) DEFAULT 0,
    Xeld INT NOT NULL,
    VeXeld INT NOT NULL, 
    CONSTRAINT FK_LuotGui_Xe FOREIGN KEY (Xeld) REFERENCES Xe(Xeld),
    CONSTRAINT FK_LuotGui_VeXe FOREIGN KEY (VeXeld) REFERENCES VeXe(VeXeld)
);
GO


INSERT INTO LoaiXe
    (TenLoaiXe, GiaTienLuot)
VALUES
    (N'Xe máy', 5000),
    (N'Ô tô', 20000);
INSERT INTO VeXe
    (MaVe, LoaiVe, TrangThai)
VALUES
    ('V001', N'Xe máy', N'TRỐNG'),
    ('V002', N'Xe máy', N'TRỐNG');
GO